[build]
  command = "yarn lint:fix && yarn test && yarn build && yarn firebase deploy --token ${FIREBASE_DEPLOY_TOKEN}"
  publish = "packages/client/build/"

[[redirects]]
  from = "/api/*"
  to = "https://us-east1-waves-production.cloudfunctions.net/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
