[build]
  command = "yarn lint:fix && yarn test && yarn build"
  publish = "packages/client/buildbuild-output/"

[[redirects]]
  from = "/api/*"
  to = "https://us-east1-waves-production.cloudfunctions.net/:splat"
  status = "200"
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = "200"
